# This if the main configuration file for Automaton.
#
# Configuration Settings:
# -----------------------
#
#
# A few things to note:
# ---------------------
#   1) You do not need to create the collections before hand.
#   2) If you use a ReplicaSet then set the following => replicaset: no
#      otherwise ONLY THE FIRST HOST will be used
#   3) Puppet Inventory Service MUST be setup on the puppetmaster in order
#      to use facter fact interpolation in ENC data.
#

# Database Configuration
# json support is coming soon
#database_type: 'mongo' or 'yaml' or 'json'
database_type:  'yaml'

# Mongo Configuration
mdb_hosts:      'localhost,mongohost001b:27017,mongohost001c:27017'
replicaset:     'no'

# Flat File Configuration
data_path:      '/opt/automaton/data/nodes'

# Database Configuration if using MongoDB
database:       'automaton'
nodecollection: 'enc'
factcollection: 'facts'

# Puppet & Facter Configuration
# Inventory Service must be setup on the puppet master in order to use fact interpolation
environment:    'production'
inventoryurl:   'https://puppet3'
inventoryport:  '8140'
enablefacts:    'false'

# Logging Configuration
logpath:        '/opt/automaton/log/automaton.log'
enablelog:      'true'
verbose:        'false'
debug:          'false'
